### ISSUE TITLE
parseAndCheckLogin 404

### ISSUE THREAD

**Issue by calvinbui** [ivkos/botyo-bundle-instagram#1]
This is the error I'm running into when using the #ig command.

Using my username/email/phone number and password. Tried with two accounts.

```botyo_1  | 2018-06-08T14:32:40.342Z - error: [CommandExecutorFilter] Command 'ig' handled by 'InstagramCommand' failed Error: parseAndCheckLogin got status code: 404. Bailing out of trying to parse response.
botyo_1  |     at /app/node_modules/facebook-chat-api/utils.js:1040:15
botyo_1  |     at tryCatcher (/app/node_modules/bluebird/js/release/util.js:16:23)
botyo_1  |     at Function.Promise.attempt.Promise.try (/app/node_modules/bluebird/js/release/method.js:39:29)
botyo_1  |     at /app/node_modules/facebook-chat-api/utils.js:987:24
botyo_1  |     at tryCatcher (/app/node_modules/bluebird/js/release/util.js:16:23)
botyo_1  |     at Promise._settlePromiseFromHandler (/app/node_modules/bluebird/js/release/promise.js:512:31)
botyo_1  |     at Promise._settlePromise (/app/node_modules/bluebird/js/release/promise.js:569:18)
botyo_1  |     at Promise._settlePromise0 (/app/node_modules/bluebird/js/release/promise.js:614:10)
botyo_1  |     at Promise._settlePromises (/app/node_modules/bluebird/js/release/promise.js:693:18)
botyo_1  |     at Async._drainQueue (/app/node_modules/bluebird/js/release/async.js:133:16)
botyo_1  |     at Async._drainQueues (/app/node_modules/bluebird/js/release/async.js:143:10)
botyo_1  |     at Immediate.Async.drainQueues (/app/node_modules/bluebird/js/release/async.js:17:14)
botyo_1  |     at runCallback (timers.js:789:20)
botyo_1  |     at tryOnImmediate (timers.js:751:5)
botyo_1  |     at processImmediate [as _immediateCallback] (timers.js:722:5)
```

**Comment by ivkos** [comment]
This Instagram API may or may not be broken and has been buggy on multiple occasions before. I'll try updating it to its latest version, and if that won't fix it, there's a new one that might be a worthy replacement:
https://github.com/jlobos/instagram-web-api

**Comment by ivkos** [comment]
@calvinbui Thank you for your report. It's fixed now. Please update the Instagram bundle to 2.0.2
